### ISSUE TITLE
README.md throwing integrity error in NC16 RC2

### ISSUE THREAD

**Issue by ndom91** [nextcloud/files_rightclick#68] opened 2019-04-22 19:09 UTC
README.md seems to be throwing integrity warnings on 0.13.0 under NC 16 RC2

```bash
$(ndo@newtelco-ndo)-(/var/www/html/nextcloud)
$(20:57)-(164Kb)$ sudo -u www-data php occ integrity:check-app files_rightclick
  - EXTRA_FILE:
    - README.md:
      - expected: 
      - current: cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
```

Is this something I (the user) can rectify?

**Comment by ricain** [comment] 2019-05-16 17:52
Yep, same error for me. Probably a duplicate of #70.

**Comment by BUG-reporter** [comment] 2019-11-19 01:00
The same is after I upgraded to Nextcloud 17.0.1. Please, fix it as possible.

**Comment by ChristophWurst** [comment] 2019-11-19 09:10
> Yep, same error for me. Probably a duplicate of #70.

@NastuzziSamy what was the "fix" and was it included in the last few releases? :)

**Comment by davidsaah** [comment] 2020-03-07 05:05
I have the same problem with Nextcloud 18

**Closed** 2023-10-17 09:23 UTC
